# Site settings
title: even the horse knew
header-img: img/sarajevo-bobsled.jpg
email: bex@pobox.com
copyright_name: Brian Exelbierd
description: "The personal ramblings of Brian Exelbierd and not his employers."
baseurl: ""
url: "http://www.winglemeyer.org"
twitter_username: bexelbie
github_username:  bexelbie
facebook_username:  
linkedin_username:  bcexelbi
email_username: bex@pobox.com

future: false

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README","vendor"]

#gems: [jekyll-feed, jekyll-paginate]
gems: [jekyll-paginate, jekyll-feed]
