# Site settings
title: even the horse knew
header-img: img/sarajevo-bobsled.jpg
email: bex@pobox.com
copyright_name: Brian Exelbierd
description: "The personal ramblings of Brian Exelbierd and not his employers."
baseurl: ""
url: "http://www.winglemeyer.org"
twitter_username: bexelbie
github_username:  bexelbie
facebook_username:  
linkedin_username:  bcexelbi
email_username: bex@pobox.com

future: false

analytics :
  provider : google 
  google : 
      tracking_id : 'UA-72767771-1'

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gemfile","Gemfile.lock","Gruntfile.js","package.json","README.md","vendor","README"]

gems: [jekyll-paginate, jekyll-feed]
